/*
	dcc decoder unittests
	
	Copyright Jeroen Vreeken (jeroen@vreeken.net), 2023

	This program is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

#define F_CPU 16000000

uint32_t DDRD;
uint32_t EICRA;
uint32_t EIMSK;
uint32_t PORTD;
uint32_t TCCR1A;
uint32_t TCCR1B;
uint32_t TCCR1C;
uint32_t TCNT1;


int tick_us = 1;
#define TICK_US tick_us

#define ISR(name) void (name)(void)

// We pick the nano for this UT
#define __AVR_ATmega328P__

/************************************/
#include "dcc_decoder.c"
/************************************/



struct test_step {
	enum dcc_decoder_state state_in;
	enum dcc_decoder_state state_out;
	uint16_t tick;

	uint8_t packet[DCC_PACKET_MAX];
	int8_t len;
	bool received_in;
	bool received_out;
};

struct test {
	char *name;
	int nr;
	int tick_us;
	struct test_step *steps;
};

struct test tests[] = {
	{ "Not a preamble", 1, 1, (struct test_step[1]){
			{ DCC_DECODER_STATE_PREAMBLE_WAIT, 	DCC_DECODER_STATE_PREAMBLE_WAIT, 3 }
		}
	
	},
	{ "Not a preamble min", 1, 1, (struct test_step[1]){
			{ DCC_DECODER_STATE_PREAMBLE_WAIT, 	DCC_DECODER_STATE_PREAMBLE_WAIT, 50 }
		}
	
	},
	{ "Not a preamble 4us min", 1, 4, (struct test_step[1]){
			{ DCC_DECODER_STATE_PREAMBLE_WAIT, 	DCC_DECODER_STATE_PREAMBLE_WAIT, 11 }
		}
	
	},
	{ "Not a preamble max", 1, 1, (struct test_step[1]){
			{ DCC_DECODER_STATE_PREAMBLE_WAIT, 	DCC_DECODER_STATE_PREAMBLE_WAIT, 65 }
		}
	
	},
	{ "Not a preamble 4us max", 1, 4, (struct test_step[1]){
			{ DCC_DECODER_STATE_PREAMBLE_WAIT, 	DCC_DECODER_STATE_PREAMBLE_WAIT, 17 }
		}
	
	},
	{ "Noise 0 ticks", 3, 1, (struct test_step[3]){
			{ DCC_DECODER_STATE_PREAMBLE_0H, 	DCC_DECODER_STATE_PREAMBLE_0H, 0 },
			{ DCC_DECODER_STATE_PREAMBLE_0H, 	DCC_DECODER_STATE_PREAMBLE_0H, 0 },
			{ DCC_DECODER_STATE_PREAMBLE_0H, 	DCC_DECODER_STATE_PREAMBLE_1, 52 }
		}
	
	},
	{ "Noise 1 ticks", 3, 1, (struct test_step[3]){
			{ DCC_DECODER_STATE_PREAMBLE_0H, 	DCC_DECODER_STATE_PREAMBLE_0H, 1 },
			{ DCC_DECODER_STATE_PREAMBLE_0H, 	DCC_DECODER_STATE_PREAMBLE_0H, 0 },
			{ DCC_DECODER_STATE_PREAMBLE_0H, 	DCC_DECODER_STATE_PREAMBLE_1, 50 }
		}
	
	},
	{ "Noise 0 ticks 4us", 3, 4, (struct test_step[3]){
			{ DCC_DECODER_STATE_PREAMBLE_0H, 	DCC_DECODER_STATE_PREAMBLE_0H, 0 },
			{ DCC_DECODER_STATE_PREAMBLE_0H, 	DCC_DECODER_STATE_PREAMBLE_0H, 0 },
			{ DCC_DECODER_STATE_PREAMBLE_0H, 	DCC_DECODER_STATE_PREAMBLE_1, 13 }
		}
	
	},
	{ "Noise 1 ticks 4us", 3, 4, (struct test_step[3]){
			{ DCC_DECODER_STATE_PREAMBLE_0H, 	DCC_DECODER_STATE_PREAMBLE_0H, 1 },
			{ DCC_DECODER_STATE_PREAMBLE_0H, 	DCC_DECODER_STATE_PREAMBLE_0H, 0 },
			{ DCC_DECODER_STATE_PREAMBLE_0H, 	DCC_DECODER_STATE_PREAMBLE_1, 12 }
		}
	
	},
	{ "Preamble", 20, 1, (struct test_step[20]){
			{ DCC_DECODER_STATE_PREAMBLE_WAIT, 	DCC_DECODER_STATE_PREAMBLE_0H, 	52 },
			{ DCC_DECODER_STATE_PREAMBLE_0H,	DCC_DECODER_STATE_PREAMBLE_1, 	55 },
			{ DCC_DECODER_STATE_PREAMBLE_1,		DCC_DECODER_STATE_PREAMBLE_1H, 	58 },
			{ DCC_DECODER_STATE_PREAMBLE_1H,	DCC_DECODER_STATE_PREAMBLE_2, 	61 },
			{ DCC_DECODER_STATE_PREAMBLE_2,		DCC_DECODER_STATE_PREAMBLE_2H, 	64 },
			{ DCC_DECODER_STATE_PREAMBLE_2H,	DCC_DECODER_STATE_PREAMBLE_3, 	61 },
			{ DCC_DECODER_STATE_PREAMBLE_3,		DCC_DECODER_STATE_PREAMBLE_3H, 	58 },
			{ DCC_DECODER_STATE_PREAMBLE_3H,	DCC_DECODER_STATE_PREAMBLE_4, 	58 },
			{ DCC_DECODER_STATE_PREAMBLE_4,		DCC_DECODER_STATE_PREAMBLE_4H, 	58 },
			{ DCC_DECODER_STATE_PREAMBLE_4H,	DCC_DECODER_STATE_PREAMBLE_5, 	58 },
			{ DCC_DECODER_STATE_PREAMBLE_5,		DCC_DECODER_STATE_PREAMBLE_5H, 	58 },
			{ DCC_DECODER_STATE_PREAMBLE_5H,	DCC_DECODER_STATE_PREAMBLE_6, 	58 },
			{ DCC_DECODER_STATE_PREAMBLE_6,		DCC_DECODER_STATE_PREAMBLE_6H, 	58 },
			{ DCC_DECODER_STATE_PREAMBLE_6H,	DCC_DECODER_STATE_PREAMBLE_7, 	58 },
			{ DCC_DECODER_STATE_PREAMBLE_7,		DCC_DECODER_STATE_PREAMBLE_7H, 	58 },
			{ DCC_DECODER_STATE_PREAMBLE_7H,	DCC_DECODER_STATE_PREAMBLE_8, 	58 },
			{ DCC_DECODER_STATE_PREAMBLE_8,		DCC_DECODER_STATE_PREAMBLE_8H, 	58 },
			{ DCC_DECODER_STATE_PREAMBLE_8H,	DCC_DECODER_STATE_PREAMBLE_9, 	58 },
			{ DCC_DECODER_STATE_PREAMBLE_9,		DCC_DECODER_STATE_PREAMBLE_9H, 	58 },
			{ DCC_DECODER_STATE_PREAMBLE_9H,	DCC_DECODER_STATE_PREAMBLE_END,	58 },
		}
	
	},
	{ "Preamble 4us", 20, 4, (struct test_step[20]){
			{ DCC_DECODER_STATE_PREAMBLE_WAIT, 	DCC_DECODER_STATE_PREAMBLE_0H, 	12 },
			{ DCC_DECODER_STATE_PREAMBLE_0H,	DCC_DECODER_STATE_PREAMBLE_1, 	13 },
			{ DCC_DECODER_STATE_PREAMBLE_1,		DCC_DECODER_STATE_PREAMBLE_1H, 	14 },
			{ DCC_DECODER_STATE_PREAMBLE_1H,	DCC_DECODER_STATE_PREAMBLE_2, 	15 },
			{ DCC_DECODER_STATE_PREAMBLE_2,		DCC_DECODER_STATE_PREAMBLE_2H, 	16 },
			{ DCC_DECODER_STATE_PREAMBLE_2H,	DCC_DECODER_STATE_PREAMBLE_3, 	15 },
			{ DCC_DECODER_STATE_PREAMBLE_3,		DCC_DECODER_STATE_PREAMBLE_3H, 	15 },
			{ DCC_DECODER_STATE_PREAMBLE_3H,	DCC_DECODER_STATE_PREAMBLE_4, 	15 },
			{ DCC_DECODER_STATE_PREAMBLE_4,		DCC_DECODER_STATE_PREAMBLE_4H, 	15 },
			{ DCC_DECODER_STATE_PREAMBLE_4H,	DCC_DECODER_STATE_PREAMBLE_5, 	15 },
			{ DCC_DECODER_STATE_PREAMBLE_5,		DCC_DECODER_STATE_PREAMBLE_5H, 	15 },
			{ DCC_DECODER_STATE_PREAMBLE_5H,	DCC_DECODER_STATE_PREAMBLE_6, 	15 },
			{ DCC_DECODER_STATE_PREAMBLE_6,		DCC_DECODER_STATE_PREAMBLE_6H, 	15 },
			{ DCC_DECODER_STATE_PREAMBLE_6H,	DCC_DECODER_STATE_PREAMBLE_7, 	15 },
			{ DCC_DECODER_STATE_PREAMBLE_7,		DCC_DECODER_STATE_PREAMBLE_7H, 	15 },
			{ DCC_DECODER_STATE_PREAMBLE_7H,	DCC_DECODER_STATE_PREAMBLE_8, 	14 },
			{ DCC_DECODER_STATE_PREAMBLE_8,		DCC_DECODER_STATE_PREAMBLE_8H, 	14 },
			{ DCC_DECODER_STATE_PREAMBLE_8H,	DCC_DECODER_STATE_PREAMBLE_9, 	14 },
			{ DCC_DECODER_STATE_PREAMBLE_9,		DCC_DECODER_STATE_PREAMBLE_9H, 	14 },
			{ DCC_DECODER_STATE_PREAMBLE_9H,	DCC_DECODER_STATE_PREAMBLE_END,	14 },
		}
	
	},
	{ "Preamble end, half start", 2, 1, (struct test_step[2]){
			{ DCC_DECODER_STATE_PREAMBLE_END, 	DCC_DECODER_STATE_START_H, 		100 },
			{ DCC_DECODER_STATE_START_H, 		DCC_DECODER_STATE_PREAMBLE_WAIT,	58 },
		}
	
	},
	{ "Preamble end, previous not handled", 1, 1, (struct test_step[1]){
			{ DCC_DECODER_STATE_PREAMBLE_END, 	DCC_DECODER_STATE_PREAMBLE_WAIT, 	100, .received_in = true },
		}
	
	},
	{ "Preamble end, start", 2, 1, (struct test_step[2]){
			{ DCC_DECODER_STATE_PREAMBLE_END, 	DCC_DECODER_STATE_START_H, 		100 },
			{ DCC_DECODER_STATE_START_H, 		DCC_DECODER_STATE_BIT0_WAIT,		100 },
		}
	
	},
	{ "Preamble end, start minimal", 2, 1, (struct test_step[2]){
			{ DCC_DECODER_STATE_PREAMBLE_END, 	DCC_DECODER_STATE_START_H, 		90 },
			{ DCC_DECODER_STATE_START_H, 		DCC_DECODER_STATE_BIT0_WAIT,		90 },
		}
	
	},
	{ "Preamble end, start maximal odd", 2, 1, (struct test_step[2]){
			{ DCC_DECODER_STATE_PREAMBLE_END, 	DCC_DECODER_STATE_START_H, 		10000 },
			{ DCC_DECODER_STATE_START_H, 		DCC_DECODER_STATE_BIT0_WAIT,		 2000 },
		}
	
	},
	{ "Preamble end, start maximal even", 2, 1, (struct test_step[2]){
			{ DCC_DECODER_STATE_PREAMBLE_END, 	DCC_DECODER_STATE_START_H, 		 2000 },
			{ DCC_DECODER_STATE_START_H, 		DCC_DECODER_STATE_BIT0_WAIT,		10000 },
		}
	
	},
	{ "Idle", 54, 1, (struct test_step[54]){
			{ DCC_DECODER_STATE_BIT0_WAIT, 		DCC_DECODER_STATE_BIT0_1, 		58  },
			{ DCC_DECODER_STATE_BIT0_1, 		DCC_DECODER_STATE_BIT1_WAIT,		58  },
			{ DCC_DECODER_STATE_BIT1_WAIT, 		DCC_DECODER_STATE_BIT1_1, 		58  },
			{ DCC_DECODER_STATE_BIT1_1, 		DCC_DECODER_STATE_BIT2_WAIT,		58  },
			{ DCC_DECODER_STATE_BIT2_WAIT, 		DCC_DECODER_STATE_BIT2_1, 		58  },
			{ DCC_DECODER_STATE_BIT2_1, 		DCC_DECODER_STATE_BIT3_WAIT,		58  },
			{ DCC_DECODER_STATE_BIT3_WAIT, 		DCC_DECODER_STATE_BIT3_1, 		58  },
			{ DCC_DECODER_STATE_BIT3_1, 		DCC_DECODER_STATE_BIT4_WAIT,		58  },
			{ DCC_DECODER_STATE_BIT4_WAIT, 		DCC_DECODER_STATE_BIT4_1, 		58  },
			{ DCC_DECODER_STATE_BIT4_1, 		DCC_DECODER_STATE_BIT5_WAIT,		58  },
			{ DCC_DECODER_STATE_BIT5_WAIT, 		DCC_DECODER_STATE_BIT5_1, 		58  },
			{ DCC_DECODER_STATE_BIT5_1, 		DCC_DECODER_STATE_BIT6_WAIT,		58  },
			{ DCC_DECODER_STATE_BIT6_WAIT, 		DCC_DECODER_STATE_BIT6_1, 		58  },
			{ DCC_DECODER_STATE_BIT6_1, 		DCC_DECODER_STATE_BIT7_WAIT,		58  },
			{ DCC_DECODER_STATE_BIT7_WAIT, 		DCC_DECODER_STATE_BIT7_1, 		58  },
			{ DCC_DECODER_STATE_BIT7_1, 		DCC_DECODER_STATE_START_WAIT,		58  },
			{ DCC_DECODER_STATE_START_WAIT, 	DCC_DECODER_STATE_START_H, 		100, { 0xff }, 1, false },
			{ DCC_DECODER_STATE_START_H, 		DCC_DECODER_STATE_BIT0_WAIT,		100, { 0xff }, 1, false },
			{ DCC_DECODER_STATE_BIT0_WAIT, 		DCC_DECODER_STATE_BIT0_0, 		100 },
			{ DCC_DECODER_STATE_BIT0_0, 		DCC_DECODER_STATE_BIT1_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT1_WAIT, 		DCC_DECODER_STATE_BIT1_0, 		100 },
			{ DCC_DECODER_STATE_BIT1_0, 		DCC_DECODER_STATE_BIT2_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT2_WAIT, 		DCC_DECODER_STATE_BIT2_0, 		100 },
			{ DCC_DECODER_STATE_BIT2_0, 		DCC_DECODER_STATE_BIT3_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT3_WAIT, 		DCC_DECODER_STATE_BIT3_0, 		100 },
			{ DCC_DECODER_STATE_BIT3_0, 		DCC_DECODER_STATE_BIT4_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT4_WAIT, 		DCC_DECODER_STATE_BIT4_0, 		100 },
			{ DCC_DECODER_STATE_BIT4_0, 		DCC_DECODER_STATE_BIT5_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT5_WAIT, 		DCC_DECODER_STATE_BIT5_0, 		100 },
			{ DCC_DECODER_STATE_BIT5_0, 		DCC_DECODER_STATE_BIT6_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT6_WAIT, 		DCC_DECODER_STATE_BIT6_0, 		100 },
			{ DCC_DECODER_STATE_BIT6_0, 		DCC_DECODER_STATE_BIT7_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT7_WAIT, 		DCC_DECODER_STATE_BIT7_0, 		100 },
			{ DCC_DECODER_STATE_BIT7_0, 		DCC_DECODER_STATE_START_WAIT,		100 },
			{ DCC_DECODER_STATE_START_WAIT, 	DCC_DECODER_STATE_START_H, 		100, { 0xff, 0x00 }, 2, false },
			{ DCC_DECODER_STATE_START_H, 		DCC_DECODER_STATE_BIT0_WAIT,		100, { 0xff, 0x00 }, 2, false },
			{ DCC_DECODER_STATE_BIT0_WAIT, 		DCC_DECODER_STATE_BIT0_1, 		58  },
			{ DCC_DECODER_STATE_BIT0_1, 		DCC_DECODER_STATE_BIT1_WAIT,		58  },
			{ DCC_DECODER_STATE_BIT1_WAIT, 		DCC_DECODER_STATE_BIT1_1, 		58  },
			{ DCC_DECODER_STATE_BIT1_1, 		DCC_DECODER_STATE_BIT2_WAIT,		58  },
			{ DCC_DECODER_STATE_BIT2_WAIT, 		DCC_DECODER_STATE_BIT2_1, 		58  },
			{ DCC_DECODER_STATE_BIT2_1, 		DCC_DECODER_STATE_BIT3_WAIT,		58  },
			{ DCC_DECODER_STATE_BIT3_WAIT, 		DCC_DECODER_STATE_BIT3_1, 		58  },
			{ DCC_DECODER_STATE_BIT3_1, 		DCC_DECODER_STATE_BIT4_WAIT,		58  },
			{ DCC_DECODER_STATE_BIT4_WAIT, 		DCC_DECODER_STATE_BIT4_1, 		58  },
			{ DCC_DECODER_STATE_BIT4_1, 		DCC_DECODER_STATE_BIT5_WAIT,		58  },
			{ DCC_DECODER_STATE_BIT5_WAIT, 		DCC_DECODER_STATE_BIT5_1, 		58  },
			{ DCC_DECODER_STATE_BIT5_1, 		DCC_DECODER_STATE_BIT6_WAIT,		58  },
			{ DCC_DECODER_STATE_BIT6_WAIT, 		DCC_DECODER_STATE_BIT6_1, 		58  },
			{ DCC_DECODER_STATE_BIT6_1, 		DCC_DECODER_STATE_BIT7_WAIT,		58  },
			{ DCC_DECODER_STATE_BIT7_WAIT, 		DCC_DECODER_STATE_BIT7_1, 		58  },
			{ DCC_DECODER_STATE_BIT7_1, 		DCC_DECODER_STATE_START_WAIT,		58  },
			{ DCC_DECODER_STATE_START_WAIT, 	DCC_DECODER_STATE_PREAMBLE_0H,		58, { 0xff, 0x00, 0xff }, 3, false, true },
			{ DCC_DECODER_STATE_PREAMBLE_0H,	DCC_DECODER_STATE_PREAMBLE_1,		58, { 0xff, 0x00, 0xff }, 3, true, true },
		}
	
	},
	{ "4 byte", 72, 1, (struct test_step[72]){
			{ DCC_DECODER_STATE_BIT0_WAIT, 		DCC_DECODER_STATE_BIT0_0, 		100 },
			{ DCC_DECODER_STATE_BIT0_0, 		DCC_DECODER_STATE_BIT1_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT1_WAIT, 		DCC_DECODER_STATE_BIT1_0, 		100 },
			{ DCC_DECODER_STATE_BIT1_0, 		DCC_DECODER_STATE_BIT2_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT2_WAIT, 		DCC_DECODER_STATE_BIT2_0, 		100 },
			{ DCC_DECODER_STATE_BIT2_0, 		DCC_DECODER_STATE_BIT3_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT3_WAIT, 		DCC_DECODER_STATE_BIT3_0, 		100 },
			{ DCC_DECODER_STATE_BIT3_0, 		DCC_DECODER_STATE_BIT4_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT4_WAIT, 		DCC_DECODER_STATE_BIT4_0, 		100 },
			{ DCC_DECODER_STATE_BIT4_0, 		DCC_DECODER_STATE_BIT5_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT5_WAIT, 		DCC_DECODER_STATE_BIT5_0, 		100 },
			{ DCC_DECODER_STATE_BIT5_0, 		DCC_DECODER_STATE_BIT6_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT6_WAIT, 		DCC_DECODER_STATE_BIT6_0, 		100 },
			{ DCC_DECODER_STATE_BIT6_0, 		DCC_DECODER_STATE_BIT7_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT7_WAIT, 		DCC_DECODER_STATE_BIT7_0, 		100 },
			{ DCC_DECODER_STATE_BIT7_0, 		DCC_DECODER_STATE_START_WAIT,		100 },
			{ DCC_DECODER_STATE_START_WAIT, 	DCC_DECODER_STATE_START_H, 		100, { 0x00 }, 1, false },
			{ DCC_DECODER_STATE_START_H, 		DCC_DECODER_STATE_BIT0_WAIT,		100, { 0x00 }, 1, false },
			{ DCC_DECODER_STATE_BIT0_WAIT, 		DCC_DECODER_STATE_BIT0_0, 		100 },
			{ DCC_DECODER_STATE_BIT0_0, 		DCC_DECODER_STATE_BIT1_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT1_WAIT, 		DCC_DECODER_STATE_BIT1_0, 		100 },
			{ DCC_DECODER_STATE_BIT1_0, 		DCC_DECODER_STATE_BIT2_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT2_WAIT, 		DCC_DECODER_STATE_BIT2_0, 		100 },
			{ DCC_DECODER_STATE_BIT2_0, 		DCC_DECODER_STATE_BIT3_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT3_WAIT, 		DCC_DECODER_STATE_BIT3_0, 		100 },
			{ DCC_DECODER_STATE_BIT3_0, 		DCC_DECODER_STATE_BIT4_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT4_WAIT, 		DCC_DECODER_STATE_BIT4_0, 		100 },
			{ DCC_DECODER_STATE_BIT4_0, 		DCC_DECODER_STATE_BIT5_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT5_WAIT, 		DCC_DECODER_STATE_BIT5_0, 		100 },
			{ DCC_DECODER_STATE_BIT5_0, 		DCC_DECODER_STATE_BIT6_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT6_WAIT, 		DCC_DECODER_STATE_BIT6_0, 		100 },
			{ DCC_DECODER_STATE_BIT6_0, 		DCC_DECODER_STATE_BIT7_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT7_WAIT, 		DCC_DECODER_STATE_BIT7_0, 		100 },
			{ DCC_DECODER_STATE_BIT7_0, 		DCC_DECODER_STATE_START_WAIT,		100 },
			{ DCC_DECODER_STATE_START_WAIT, 	DCC_DECODER_STATE_START_H, 		100, { 0x00, 0x00 }, 2, false },
			{ DCC_DECODER_STATE_START_H, 		DCC_DECODER_STATE_BIT0_WAIT,		100, { 0x00, 0x00 }, 2, false },
			{ DCC_DECODER_STATE_BIT0_WAIT, 		DCC_DECODER_STATE_BIT0_0, 		100 },
			{ DCC_DECODER_STATE_BIT0_0, 		DCC_DECODER_STATE_BIT1_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT1_WAIT, 		DCC_DECODER_STATE_BIT1_0, 		100 },
			{ DCC_DECODER_STATE_BIT1_0, 		DCC_DECODER_STATE_BIT2_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT2_WAIT, 		DCC_DECODER_STATE_BIT2_0, 		100 },
			{ DCC_DECODER_STATE_BIT2_0, 		DCC_DECODER_STATE_BIT3_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT3_WAIT, 		DCC_DECODER_STATE_BIT3_0, 		100 },
			{ DCC_DECODER_STATE_BIT3_0, 		DCC_DECODER_STATE_BIT4_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT4_WAIT, 		DCC_DECODER_STATE_BIT4_0, 		100 },
			{ DCC_DECODER_STATE_BIT4_0, 		DCC_DECODER_STATE_BIT5_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT5_WAIT, 		DCC_DECODER_STATE_BIT5_0, 		100 },
			{ DCC_DECODER_STATE_BIT5_0, 		DCC_DECODER_STATE_BIT6_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT6_WAIT, 		DCC_DECODER_STATE_BIT6_0, 		100 },
			{ DCC_DECODER_STATE_BIT6_0, 		DCC_DECODER_STATE_BIT7_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT7_WAIT, 		DCC_DECODER_STATE_BIT7_0, 		100 },
			{ DCC_DECODER_STATE_BIT7_0, 		DCC_DECODER_STATE_START_WAIT,		100 },
			{ DCC_DECODER_STATE_START_WAIT, 	DCC_DECODER_STATE_START_H, 		100, { 0x00, 0x00, 0x00 }, 3, false },
			{ DCC_DECODER_STATE_START_H, 		DCC_DECODER_STATE_BIT0_WAIT,		100, { 0x00, 0x00, 0x00 }, 3, false },
			{ DCC_DECODER_STATE_BIT0_WAIT, 		DCC_DECODER_STATE_BIT0_0, 		100 },
			{ DCC_DECODER_STATE_BIT0_0, 		DCC_DECODER_STATE_BIT1_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT1_WAIT, 		DCC_DECODER_STATE_BIT1_0, 		100 },
			{ DCC_DECODER_STATE_BIT1_0, 		DCC_DECODER_STATE_BIT2_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT2_WAIT, 		DCC_DECODER_STATE_BIT2_0, 		100 },
			{ DCC_DECODER_STATE_BIT2_0, 		DCC_DECODER_STATE_BIT3_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT3_WAIT, 		DCC_DECODER_STATE_BIT3_0, 		100 },
			{ DCC_DECODER_STATE_BIT3_0, 		DCC_DECODER_STATE_BIT4_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT4_WAIT, 		DCC_DECODER_STATE_BIT4_0, 		100 },
			{ DCC_DECODER_STATE_BIT4_0, 		DCC_DECODER_STATE_BIT5_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT5_WAIT, 		DCC_DECODER_STATE_BIT5_0, 		100 },
			{ DCC_DECODER_STATE_BIT5_0, 		DCC_DECODER_STATE_BIT6_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT6_WAIT, 		DCC_DECODER_STATE_BIT6_0, 		100 },
			{ DCC_DECODER_STATE_BIT6_0, 		DCC_DECODER_STATE_BIT7_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT7_WAIT, 		DCC_DECODER_STATE_BIT7_0, 		100 },
			{ DCC_DECODER_STATE_BIT7_0, 		DCC_DECODER_STATE_START_WAIT,		100 },
			{ DCC_DECODER_STATE_START_WAIT, 	DCC_DECODER_STATE_PREAMBLE_0H,		58, { 0x00, 0x00, 0x00, 0x00 }, 4, false, true },
			{ DCC_DECODER_STATE_PREAMBLE_0H,	DCC_DECODER_STATE_PREAMBLE_1,		58, { 0x00, 0x00, 0x00, 0x00 }, 4, true, true },
		}	
	},
	{ "5 byte", 90, 1, (struct test_step[90]){
			{ DCC_DECODER_STATE_BIT0_WAIT, 		DCC_DECODER_STATE_BIT0_0, 		100 },
			{ DCC_DECODER_STATE_BIT0_0, 		DCC_DECODER_STATE_BIT1_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT1_WAIT, 		DCC_DECODER_STATE_BIT1_0, 		100 },
			{ DCC_DECODER_STATE_BIT1_0, 		DCC_DECODER_STATE_BIT2_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT2_WAIT, 		DCC_DECODER_STATE_BIT2_0, 		100 },
			{ DCC_DECODER_STATE_BIT2_0, 		DCC_DECODER_STATE_BIT3_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT3_WAIT, 		DCC_DECODER_STATE_BIT3_0, 		100 },
			{ DCC_DECODER_STATE_BIT3_0, 		DCC_DECODER_STATE_BIT4_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT4_WAIT, 		DCC_DECODER_STATE_BIT4_0, 		100 },
			{ DCC_DECODER_STATE_BIT4_0, 		DCC_DECODER_STATE_BIT5_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT5_WAIT, 		DCC_DECODER_STATE_BIT5_0, 		100 },
			{ DCC_DECODER_STATE_BIT5_0, 		DCC_DECODER_STATE_BIT6_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT6_WAIT, 		DCC_DECODER_STATE_BIT6_0, 		100 },
			{ DCC_DECODER_STATE_BIT6_0, 		DCC_DECODER_STATE_BIT7_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT7_WAIT, 		DCC_DECODER_STATE_BIT7_0, 		100 },
			{ DCC_DECODER_STATE_BIT7_0, 		DCC_DECODER_STATE_START_WAIT,		100 },
			{ DCC_DECODER_STATE_START_WAIT, 	DCC_DECODER_STATE_START_H, 		100, { 0x00 }, 1, false },
			{ DCC_DECODER_STATE_START_H, 		DCC_DECODER_STATE_BIT0_WAIT,		100, { 0x00 }, 1, false },
			{ DCC_DECODER_STATE_BIT0_WAIT, 		DCC_DECODER_STATE_BIT0_0, 		100 },
			{ DCC_DECODER_STATE_BIT0_0, 		DCC_DECODER_STATE_BIT1_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT1_WAIT, 		DCC_DECODER_STATE_BIT1_0, 		100 },
			{ DCC_DECODER_STATE_BIT1_0, 		DCC_DECODER_STATE_BIT2_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT2_WAIT, 		DCC_DECODER_STATE_BIT2_0, 		100 },
			{ DCC_DECODER_STATE_BIT2_0, 		DCC_DECODER_STATE_BIT3_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT3_WAIT, 		DCC_DECODER_STATE_BIT3_0, 		100 },
			{ DCC_DECODER_STATE_BIT3_0, 		DCC_DECODER_STATE_BIT4_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT4_WAIT, 		DCC_DECODER_STATE_BIT4_0, 		100 },
			{ DCC_DECODER_STATE_BIT4_0, 		DCC_DECODER_STATE_BIT5_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT5_WAIT, 		DCC_DECODER_STATE_BIT5_0, 		100 },
			{ DCC_DECODER_STATE_BIT5_0, 		DCC_DECODER_STATE_BIT6_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT6_WAIT, 		DCC_DECODER_STATE_BIT6_0, 		100 },
			{ DCC_DECODER_STATE_BIT6_0, 		DCC_DECODER_STATE_BIT7_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT7_WAIT, 		DCC_DECODER_STATE_BIT7_0, 		100 },
			{ DCC_DECODER_STATE_BIT7_0, 		DCC_DECODER_STATE_START_WAIT,		100 },
			{ DCC_DECODER_STATE_START_WAIT, 	DCC_DECODER_STATE_START_H, 		100, { 0x00, 0x00 }, 2, false },
			{ DCC_DECODER_STATE_START_H, 		DCC_DECODER_STATE_BIT0_WAIT,		100, { 0x00, 0x00 }, 2, false },
			{ DCC_DECODER_STATE_BIT0_WAIT, 		DCC_DECODER_STATE_BIT0_0, 		100 },
			{ DCC_DECODER_STATE_BIT0_0, 		DCC_DECODER_STATE_BIT1_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT1_WAIT, 		DCC_DECODER_STATE_BIT1_0, 		100 },
			{ DCC_DECODER_STATE_BIT1_0, 		DCC_DECODER_STATE_BIT2_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT2_WAIT, 		DCC_DECODER_STATE_BIT2_0, 		100 },
			{ DCC_DECODER_STATE_BIT2_0, 		DCC_DECODER_STATE_BIT3_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT3_WAIT, 		DCC_DECODER_STATE_BIT3_0, 		100 },
			{ DCC_DECODER_STATE_BIT3_0, 		DCC_DECODER_STATE_BIT4_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT4_WAIT, 		DCC_DECODER_STATE_BIT4_0, 		100 },
			{ DCC_DECODER_STATE_BIT4_0, 		DCC_DECODER_STATE_BIT5_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT5_WAIT, 		DCC_DECODER_STATE_BIT5_0, 		100 },
			{ DCC_DECODER_STATE_BIT5_0, 		DCC_DECODER_STATE_BIT6_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT6_WAIT, 		DCC_DECODER_STATE_BIT6_0, 		100 },
			{ DCC_DECODER_STATE_BIT6_0, 		DCC_DECODER_STATE_BIT7_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT7_WAIT, 		DCC_DECODER_STATE_BIT7_0, 		100 },
			{ DCC_DECODER_STATE_BIT7_0, 		DCC_DECODER_STATE_START_WAIT,		100 },
			{ DCC_DECODER_STATE_START_WAIT, 	DCC_DECODER_STATE_START_H, 		100, { 0x00, 0x00, 0x00 }, 3, false },
			{ DCC_DECODER_STATE_START_H, 		DCC_DECODER_STATE_BIT0_WAIT,		100, { 0x00, 0x00, 0x00 }, 3, false },
			{ DCC_DECODER_STATE_BIT0_WAIT, 		DCC_DECODER_STATE_BIT0_0, 		100 },
			{ DCC_DECODER_STATE_BIT0_0, 		DCC_DECODER_STATE_BIT1_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT1_WAIT, 		DCC_DECODER_STATE_BIT1_0, 		100 },
			{ DCC_DECODER_STATE_BIT1_0, 		DCC_DECODER_STATE_BIT2_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT2_WAIT, 		DCC_DECODER_STATE_BIT2_0, 		100 },
			{ DCC_DECODER_STATE_BIT2_0, 		DCC_DECODER_STATE_BIT3_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT3_WAIT, 		DCC_DECODER_STATE_BIT3_0, 		100 },
			{ DCC_DECODER_STATE_BIT3_0, 		DCC_DECODER_STATE_BIT4_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT4_WAIT, 		DCC_DECODER_STATE_BIT4_0, 		100 },
			{ DCC_DECODER_STATE_BIT4_0, 		DCC_DECODER_STATE_BIT5_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT5_WAIT, 		DCC_DECODER_STATE_BIT5_0, 		100 },
			{ DCC_DECODER_STATE_BIT5_0, 		DCC_DECODER_STATE_BIT6_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT6_WAIT, 		DCC_DECODER_STATE_BIT6_0, 		100 },
			{ DCC_DECODER_STATE_BIT6_0, 		DCC_DECODER_STATE_BIT7_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT7_WAIT, 		DCC_DECODER_STATE_BIT7_0, 		100 },
			{ DCC_DECODER_STATE_BIT7_0, 		DCC_DECODER_STATE_START_WAIT,		100 },
			{ DCC_DECODER_STATE_START_WAIT, 	DCC_DECODER_STATE_START_H, 		100, { 0x00, 0x00, 0x00, 0x00 }, 4, false },
			{ DCC_DECODER_STATE_START_H, 		DCC_DECODER_STATE_BIT0_WAIT,		100, { 0x00, 0x00, 0x00, 0x00 }, 4, false },
			{ DCC_DECODER_STATE_BIT0_WAIT, 		DCC_DECODER_STATE_BIT0_0, 		100 },
			{ DCC_DECODER_STATE_BIT0_0, 		DCC_DECODER_STATE_BIT1_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT1_WAIT, 		DCC_DECODER_STATE_BIT1_0, 		100 },
			{ DCC_DECODER_STATE_BIT1_0, 		DCC_DECODER_STATE_BIT2_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT2_WAIT, 		DCC_DECODER_STATE_BIT2_0, 		100 },
			{ DCC_DECODER_STATE_BIT2_0, 		DCC_DECODER_STATE_BIT3_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT3_WAIT, 		DCC_DECODER_STATE_BIT3_0, 		100 },
			{ DCC_DECODER_STATE_BIT3_0, 		DCC_DECODER_STATE_BIT4_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT4_WAIT, 		DCC_DECODER_STATE_BIT4_0, 		100 },
			{ DCC_DECODER_STATE_BIT4_0, 		DCC_DECODER_STATE_BIT5_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT5_WAIT, 		DCC_DECODER_STATE_BIT5_0, 		100 },
			{ DCC_DECODER_STATE_BIT5_0, 		DCC_DECODER_STATE_BIT6_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT6_WAIT, 		DCC_DECODER_STATE_BIT6_0, 		100 },
			{ DCC_DECODER_STATE_BIT6_0, 		DCC_DECODER_STATE_BIT7_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT7_WAIT, 		DCC_DECODER_STATE_BIT7_0, 		100 },
			{ DCC_DECODER_STATE_BIT7_0, 		DCC_DECODER_STATE_START_WAIT,		100 },
			{ DCC_DECODER_STATE_START_WAIT, 	DCC_DECODER_STATE_PREAMBLE_0H,		58, { 0x00, 0x00, 0x00, 0x00, 0x00 }, 5, false, true },
			{ DCC_DECODER_STATE_PREAMBLE_0H,	DCC_DECODER_STATE_PREAMBLE_1,		58, { 0x00, 0x00, 0x00, 0x00, 0x00 }, 5, true, true },
		}
	
	},

	{ "6 byte", 108, 1, (struct test_step[108]){
			{ DCC_DECODER_STATE_BIT0_WAIT, 		DCC_DECODER_STATE_BIT0_0, 		100 },
			{ DCC_DECODER_STATE_BIT0_0, 		DCC_DECODER_STATE_BIT1_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT1_WAIT, 		DCC_DECODER_STATE_BIT1_0, 		100 },
			{ DCC_DECODER_STATE_BIT1_0, 		DCC_DECODER_STATE_BIT2_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT2_WAIT, 		DCC_DECODER_STATE_BIT2_0, 		100 },
			{ DCC_DECODER_STATE_BIT2_0, 		DCC_DECODER_STATE_BIT3_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT3_WAIT, 		DCC_DECODER_STATE_BIT3_0, 		100 },
			{ DCC_DECODER_STATE_BIT3_0, 		DCC_DECODER_STATE_BIT4_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT4_WAIT, 		DCC_DECODER_STATE_BIT4_0, 		100 },
			{ DCC_DECODER_STATE_BIT4_0, 		DCC_DECODER_STATE_BIT5_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT5_WAIT, 		DCC_DECODER_STATE_BIT5_0, 		100 },
			{ DCC_DECODER_STATE_BIT5_0, 		DCC_DECODER_STATE_BIT6_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT6_WAIT, 		DCC_DECODER_STATE_BIT6_0, 		100 },
			{ DCC_DECODER_STATE_BIT6_0, 		DCC_DECODER_STATE_BIT7_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT7_WAIT, 		DCC_DECODER_STATE_BIT7_0, 		100 },
			{ DCC_DECODER_STATE_BIT7_0, 		DCC_DECODER_STATE_START_WAIT,		100 },
			{ DCC_DECODER_STATE_START_WAIT, 	DCC_DECODER_STATE_START_H, 		100, { 0x00 }, 1, false },
			{ DCC_DECODER_STATE_START_H, 		DCC_DECODER_STATE_BIT0_WAIT,		100, { 0x00 }, 1, false },
			{ DCC_DECODER_STATE_BIT0_WAIT, 		DCC_DECODER_STATE_BIT0_0, 		100 },
			{ DCC_DECODER_STATE_BIT0_0, 		DCC_DECODER_STATE_BIT1_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT1_WAIT, 		DCC_DECODER_STATE_BIT1_0, 		100 },
			{ DCC_DECODER_STATE_BIT1_0, 		DCC_DECODER_STATE_BIT2_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT2_WAIT, 		DCC_DECODER_STATE_BIT2_0, 		100 },
			{ DCC_DECODER_STATE_BIT2_0, 		DCC_DECODER_STATE_BIT3_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT3_WAIT, 		DCC_DECODER_STATE_BIT3_0, 		100 },
			{ DCC_DECODER_STATE_BIT3_0, 		DCC_DECODER_STATE_BIT4_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT4_WAIT, 		DCC_DECODER_STATE_BIT4_0, 		100 },
			{ DCC_DECODER_STATE_BIT4_0, 		DCC_DECODER_STATE_BIT5_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT5_WAIT, 		DCC_DECODER_STATE_BIT5_0, 		100 },
			{ DCC_DECODER_STATE_BIT5_0, 		DCC_DECODER_STATE_BIT6_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT6_WAIT, 		DCC_DECODER_STATE_BIT6_0, 		100 },
			{ DCC_DECODER_STATE_BIT6_0, 		DCC_DECODER_STATE_BIT7_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT7_WAIT, 		DCC_DECODER_STATE_BIT7_0, 		100 },
			{ DCC_DECODER_STATE_BIT7_0, 		DCC_DECODER_STATE_START_WAIT,		100 },
			{ DCC_DECODER_STATE_START_WAIT, 	DCC_DECODER_STATE_START_H, 		100, { 0x00, 0x00 }, 2, false },
			{ DCC_DECODER_STATE_START_H, 		DCC_DECODER_STATE_BIT0_WAIT,		100, { 0x00, 0x00 }, 2, false },
			{ DCC_DECODER_STATE_BIT0_WAIT, 		DCC_DECODER_STATE_BIT0_0, 		100 },
			{ DCC_DECODER_STATE_BIT0_0, 		DCC_DECODER_STATE_BIT1_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT1_WAIT, 		DCC_DECODER_STATE_BIT1_0, 		100 },
			{ DCC_DECODER_STATE_BIT1_0, 		DCC_DECODER_STATE_BIT2_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT2_WAIT, 		DCC_DECODER_STATE_BIT2_0, 		100 },
			{ DCC_DECODER_STATE_BIT2_0, 		DCC_DECODER_STATE_BIT3_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT3_WAIT, 		DCC_DECODER_STATE_BIT3_0, 		100 },
			{ DCC_DECODER_STATE_BIT3_0, 		DCC_DECODER_STATE_BIT4_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT4_WAIT, 		DCC_DECODER_STATE_BIT4_0, 		100 },
			{ DCC_DECODER_STATE_BIT4_0, 		DCC_DECODER_STATE_BIT5_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT5_WAIT, 		DCC_DECODER_STATE_BIT5_0, 		100 },
			{ DCC_DECODER_STATE_BIT5_0, 		DCC_DECODER_STATE_BIT6_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT6_WAIT, 		DCC_DECODER_STATE_BIT6_0, 		100 },
			{ DCC_DECODER_STATE_BIT6_0, 		DCC_DECODER_STATE_BIT7_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT7_WAIT, 		DCC_DECODER_STATE_BIT7_0, 		100 },
			{ DCC_DECODER_STATE_BIT7_0, 		DCC_DECODER_STATE_START_WAIT,		100 },
			{ DCC_DECODER_STATE_START_WAIT, 	DCC_DECODER_STATE_START_H, 		100, { 0x00, 0x00, 0x00 }, 3, false },
			{ DCC_DECODER_STATE_START_H, 		DCC_DECODER_STATE_BIT0_WAIT,		100, { 0x00, 0x00, 0x00 }, 3, false },
			{ DCC_DECODER_STATE_BIT0_WAIT, 		DCC_DECODER_STATE_BIT0_0, 		100 },
			{ DCC_DECODER_STATE_BIT0_0, 		DCC_DECODER_STATE_BIT1_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT1_WAIT, 		DCC_DECODER_STATE_BIT1_0, 		100 },
			{ DCC_DECODER_STATE_BIT1_0, 		DCC_DECODER_STATE_BIT2_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT2_WAIT, 		DCC_DECODER_STATE_BIT2_0, 		100 },
			{ DCC_DECODER_STATE_BIT2_0, 		DCC_DECODER_STATE_BIT3_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT3_WAIT, 		DCC_DECODER_STATE_BIT3_0, 		100 },
			{ DCC_DECODER_STATE_BIT3_0, 		DCC_DECODER_STATE_BIT4_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT4_WAIT, 		DCC_DECODER_STATE_BIT4_0, 		100 },
			{ DCC_DECODER_STATE_BIT4_0, 		DCC_DECODER_STATE_BIT5_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT5_WAIT, 		DCC_DECODER_STATE_BIT5_0, 		100 },
			{ DCC_DECODER_STATE_BIT5_0, 		DCC_DECODER_STATE_BIT6_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT6_WAIT, 		DCC_DECODER_STATE_BIT6_0, 		100 },
			{ DCC_DECODER_STATE_BIT6_0, 		DCC_DECODER_STATE_BIT7_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT7_WAIT, 		DCC_DECODER_STATE_BIT7_0, 		100 },
			{ DCC_DECODER_STATE_BIT7_0, 		DCC_DECODER_STATE_START_WAIT,		100 },
			{ DCC_DECODER_STATE_START_WAIT, 	DCC_DECODER_STATE_START_H, 		100, { 0x00, 0x00, 0x00, 0x00 }, 4, false },
			{ DCC_DECODER_STATE_START_H, 		DCC_DECODER_STATE_BIT0_WAIT,		100, { 0x00, 0x00, 0x00, 0x00 }, 4, false },
			{ DCC_DECODER_STATE_BIT0_WAIT, 		DCC_DECODER_STATE_BIT0_0, 		100 },
			{ DCC_DECODER_STATE_BIT0_0, 		DCC_DECODER_STATE_BIT1_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT1_WAIT, 		DCC_DECODER_STATE_BIT1_0, 		100 },
			{ DCC_DECODER_STATE_BIT1_0, 		DCC_DECODER_STATE_BIT2_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT2_WAIT, 		DCC_DECODER_STATE_BIT2_0, 		100 },
			{ DCC_DECODER_STATE_BIT2_0, 		DCC_DECODER_STATE_BIT3_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT3_WAIT, 		DCC_DECODER_STATE_BIT3_0, 		100 },
			{ DCC_DECODER_STATE_BIT3_0, 		DCC_DECODER_STATE_BIT4_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT4_WAIT, 		DCC_DECODER_STATE_BIT4_0, 		100 },
			{ DCC_DECODER_STATE_BIT4_0, 		DCC_DECODER_STATE_BIT5_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT5_WAIT, 		DCC_DECODER_STATE_BIT5_0, 		100 },
			{ DCC_DECODER_STATE_BIT5_0, 		DCC_DECODER_STATE_BIT6_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT6_WAIT, 		DCC_DECODER_STATE_BIT6_0, 		100 },
			{ DCC_DECODER_STATE_BIT6_0, 		DCC_DECODER_STATE_BIT7_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT7_WAIT, 		DCC_DECODER_STATE_BIT7_0, 		100 },
			{ DCC_DECODER_STATE_BIT7_0, 		DCC_DECODER_STATE_START_WAIT,		100 },
			{ DCC_DECODER_STATE_START_WAIT, 	DCC_DECODER_STATE_START_H, 		100, { 0x00, 0x00, 0x00, 0x00, 0x00 }, 5, false },
			{ DCC_DECODER_STATE_START_H, 		DCC_DECODER_STATE_BIT0_WAIT,		100, { 0x00, 0x00, 0x00, 0x00, 0x00 }, 5, false },
			{ DCC_DECODER_STATE_BIT0_WAIT, 		DCC_DECODER_STATE_BIT0_0, 		100 },
			{ DCC_DECODER_STATE_BIT0_0, 		DCC_DECODER_STATE_BIT1_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT1_WAIT, 		DCC_DECODER_STATE_BIT1_0, 		100 },
			{ DCC_DECODER_STATE_BIT1_0, 		DCC_DECODER_STATE_BIT2_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT2_WAIT, 		DCC_DECODER_STATE_BIT2_0, 		100 },
			{ DCC_DECODER_STATE_BIT2_0, 		DCC_DECODER_STATE_BIT3_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT3_WAIT, 		DCC_DECODER_STATE_BIT3_0, 		100 },
			{ DCC_DECODER_STATE_BIT3_0, 		DCC_DECODER_STATE_BIT4_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT4_WAIT, 		DCC_DECODER_STATE_BIT4_0, 		100 },
			{ DCC_DECODER_STATE_BIT4_0, 		DCC_DECODER_STATE_BIT5_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT5_WAIT, 		DCC_DECODER_STATE_BIT5_0, 		100 },
			{ DCC_DECODER_STATE_BIT5_0, 		DCC_DECODER_STATE_BIT6_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT6_WAIT, 		DCC_DECODER_STATE_BIT6_0, 		100 },
			{ DCC_DECODER_STATE_BIT6_0, 		DCC_DECODER_STATE_BIT7_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT7_WAIT, 		DCC_DECODER_STATE_BIT7_0, 		100 },
			{ DCC_DECODER_STATE_BIT7_0, 		DCC_DECODER_STATE_START_WAIT,		100 },
			{ DCC_DECODER_STATE_START_WAIT, 	DCC_DECODER_STATE_PREAMBLE_0H,		58, { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, 6, false, true },
			{ DCC_DECODER_STATE_PREAMBLE_0H,	DCC_DECODER_STATE_PREAMBLE_1,		58, { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, 6, true, true },
		}
	},

	{ "7 byte (to big)", 146, 1, (struct test_step[146]){
			{ DCC_DECODER_STATE_BIT0_WAIT, 		DCC_DECODER_STATE_BIT0_0, 		100 },
			{ DCC_DECODER_STATE_BIT0_0, 		DCC_DECODER_STATE_BIT1_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT1_WAIT, 		DCC_DECODER_STATE_BIT1_0, 		100 },
			{ DCC_DECODER_STATE_BIT1_0, 		DCC_DECODER_STATE_BIT2_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT2_WAIT, 		DCC_DECODER_STATE_BIT2_0, 		100 },
			{ DCC_DECODER_STATE_BIT2_0, 		DCC_DECODER_STATE_BIT3_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT3_WAIT, 		DCC_DECODER_STATE_BIT3_0, 		100 },
			{ DCC_DECODER_STATE_BIT3_0, 		DCC_DECODER_STATE_BIT4_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT4_WAIT, 		DCC_DECODER_STATE_BIT4_0, 		100 },
			{ DCC_DECODER_STATE_BIT4_0, 		DCC_DECODER_STATE_BIT5_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT5_WAIT, 		DCC_DECODER_STATE_BIT5_0, 		100 },
			{ DCC_DECODER_STATE_BIT5_0, 		DCC_DECODER_STATE_BIT6_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT6_WAIT, 		DCC_DECODER_STATE_BIT6_0, 		100 },
			{ DCC_DECODER_STATE_BIT6_0, 		DCC_DECODER_STATE_BIT7_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT7_WAIT, 		DCC_DECODER_STATE_BIT7_0, 		100 },
			{ DCC_DECODER_STATE_BIT7_0, 		DCC_DECODER_STATE_START_WAIT,		100 },
			{ DCC_DECODER_STATE_START_WAIT, 	DCC_DECODER_STATE_START_H, 		100, { 0x00 }, 1, false },
			{ DCC_DECODER_STATE_START_H, 		DCC_DECODER_STATE_BIT0_WAIT,		100, { 0x00 }, 1, false },
			{ DCC_DECODER_STATE_BIT0_WAIT, 		DCC_DECODER_STATE_BIT0_0, 		100 },
			{ DCC_DECODER_STATE_BIT0_0, 		DCC_DECODER_STATE_BIT1_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT1_WAIT, 		DCC_DECODER_STATE_BIT1_0, 		100 },
			{ DCC_DECODER_STATE_BIT1_0, 		DCC_DECODER_STATE_BIT2_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT2_WAIT, 		DCC_DECODER_STATE_BIT2_0, 		100 },
			{ DCC_DECODER_STATE_BIT2_0, 		DCC_DECODER_STATE_BIT3_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT3_WAIT, 		DCC_DECODER_STATE_BIT3_0, 		100 },
			{ DCC_DECODER_STATE_BIT3_0, 		DCC_DECODER_STATE_BIT4_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT4_WAIT, 		DCC_DECODER_STATE_BIT4_0, 		100 },
			{ DCC_DECODER_STATE_BIT4_0, 		DCC_DECODER_STATE_BIT5_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT5_WAIT, 		DCC_DECODER_STATE_BIT5_0, 		100 },
			{ DCC_DECODER_STATE_BIT5_0, 		DCC_DECODER_STATE_BIT6_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT6_WAIT, 		DCC_DECODER_STATE_BIT6_0, 		100 },
			{ DCC_DECODER_STATE_BIT6_0, 		DCC_DECODER_STATE_BIT7_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT7_WAIT, 		DCC_DECODER_STATE_BIT7_0, 		100 },
			{ DCC_DECODER_STATE_BIT7_0, 		DCC_DECODER_STATE_START_WAIT,		100 },
			{ DCC_DECODER_STATE_START_WAIT, 	DCC_DECODER_STATE_START_H, 		100, { 0x00, 0x00 }, 2, false },
			{ DCC_DECODER_STATE_START_H, 		DCC_DECODER_STATE_BIT0_WAIT,		100, { 0x00, 0x00 }, 2, false },
			{ DCC_DECODER_STATE_BIT0_WAIT, 		DCC_DECODER_STATE_BIT0_0, 		100 },
			{ DCC_DECODER_STATE_BIT0_0, 		DCC_DECODER_STATE_BIT1_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT1_WAIT, 		DCC_DECODER_STATE_BIT1_0, 		100 },
			{ DCC_DECODER_STATE_BIT1_0, 		DCC_DECODER_STATE_BIT2_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT2_WAIT, 		DCC_DECODER_STATE_BIT2_0, 		100 },
			{ DCC_DECODER_STATE_BIT2_0, 		DCC_DECODER_STATE_BIT3_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT3_WAIT, 		DCC_DECODER_STATE_BIT3_0, 		100 },
			{ DCC_DECODER_STATE_BIT3_0, 		DCC_DECODER_STATE_BIT4_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT4_WAIT, 		DCC_DECODER_STATE_BIT4_0, 		100 },
			{ DCC_DECODER_STATE_BIT4_0, 		DCC_DECODER_STATE_BIT5_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT5_WAIT, 		DCC_DECODER_STATE_BIT5_0, 		100 },
			{ DCC_DECODER_STATE_BIT5_0, 		DCC_DECODER_STATE_BIT6_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT6_WAIT, 		DCC_DECODER_STATE_BIT6_0, 		100 },
			{ DCC_DECODER_STATE_BIT6_0, 		DCC_DECODER_STATE_BIT7_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT7_WAIT, 		DCC_DECODER_STATE_BIT7_0, 		100 },
			{ DCC_DECODER_STATE_BIT7_0, 		DCC_DECODER_STATE_START_WAIT,		100 },
			{ DCC_DECODER_STATE_START_WAIT, 	DCC_DECODER_STATE_START_H, 		100, { 0x00, 0x00, 0x00 }, 3, false },
			{ DCC_DECODER_STATE_START_H, 		DCC_DECODER_STATE_BIT0_WAIT,		100, { 0x00, 0x00, 0x00 }, 3, false },
			{ DCC_DECODER_STATE_BIT0_WAIT, 		DCC_DECODER_STATE_BIT0_0, 		100 },
			{ DCC_DECODER_STATE_BIT0_0, 		DCC_DECODER_STATE_BIT1_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT1_WAIT, 		DCC_DECODER_STATE_BIT1_0, 		100 },
			{ DCC_DECODER_STATE_BIT1_0, 		DCC_DECODER_STATE_BIT2_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT2_WAIT, 		DCC_DECODER_STATE_BIT2_0, 		100 },
			{ DCC_DECODER_STATE_BIT2_0, 		DCC_DECODER_STATE_BIT3_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT3_WAIT, 		DCC_DECODER_STATE_BIT3_0, 		100 },
			{ DCC_DECODER_STATE_BIT3_0, 		DCC_DECODER_STATE_BIT4_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT4_WAIT, 		DCC_DECODER_STATE_BIT4_0, 		100 },
			{ DCC_DECODER_STATE_BIT4_0, 		DCC_DECODER_STATE_BIT5_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT5_WAIT, 		DCC_DECODER_STATE_BIT5_0, 		100 },
			{ DCC_DECODER_STATE_BIT5_0, 		DCC_DECODER_STATE_BIT6_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT6_WAIT, 		DCC_DECODER_STATE_BIT6_0, 		100 },
			{ DCC_DECODER_STATE_BIT6_0, 		DCC_DECODER_STATE_BIT7_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT7_WAIT, 		DCC_DECODER_STATE_BIT7_0, 		100 },
			{ DCC_DECODER_STATE_BIT7_0, 		DCC_DECODER_STATE_START_WAIT,		100 },
			{ DCC_DECODER_STATE_START_WAIT, 	DCC_DECODER_STATE_START_H, 		100, { 0x00, 0x00, 0x00, 0x00 }, 4, false },
			{ DCC_DECODER_STATE_START_H, 		DCC_DECODER_STATE_BIT0_WAIT,		100, { 0x00, 0x00, 0x00, 0x00 }, 4, false },
			{ DCC_DECODER_STATE_BIT0_WAIT, 		DCC_DECODER_STATE_BIT0_0, 		100 },
			{ DCC_DECODER_STATE_BIT0_0, 		DCC_DECODER_STATE_BIT1_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT1_WAIT, 		DCC_DECODER_STATE_BIT1_0, 		100 },
			{ DCC_DECODER_STATE_BIT1_0, 		DCC_DECODER_STATE_BIT2_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT2_WAIT, 		DCC_DECODER_STATE_BIT2_0, 		100 },
			{ DCC_DECODER_STATE_BIT2_0, 		DCC_DECODER_STATE_BIT3_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT3_WAIT, 		DCC_DECODER_STATE_BIT3_0, 		100 },
			{ DCC_DECODER_STATE_BIT3_0, 		DCC_DECODER_STATE_BIT4_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT4_WAIT, 		DCC_DECODER_STATE_BIT4_0, 		100 },
			{ DCC_DECODER_STATE_BIT4_0, 		DCC_DECODER_STATE_BIT5_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT5_WAIT, 		DCC_DECODER_STATE_BIT5_0, 		100 },
			{ DCC_DECODER_STATE_BIT5_0, 		DCC_DECODER_STATE_BIT6_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT6_WAIT, 		DCC_DECODER_STATE_BIT6_0, 		100 },
			{ DCC_DECODER_STATE_BIT6_0, 		DCC_DECODER_STATE_BIT7_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT7_WAIT, 		DCC_DECODER_STATE_BIT7_0, 		100 },
			{ DCC_DECODER_STATE_BIT7_0, 		DCC_DECODER_STATE_START_WAIT,		100 },
			{ DCC_DECODER_STATE_START_WAIT, 	DCC_DECODER_STATE_START_H, 		100, { 0x00, 0x00, 0x00, 0x00, 0x00 }, 5, false },
			{ DCC_DECODER_STATE_START_H, 		DCC_DECODER_STATE_BIT0_WAIT,		100, { 0x00, 0x00, 0x00, 0x00, 0x00 }, 5, false },
			{ DCC_DECODER_STATE_BIT0_WAIT, 		DCC_DECODER_STATE_BIT0_0, 		100 },
			{ DCC_DECODER_STATE_BIT0_0, 		DCC_DECODER_STATE_BIT1_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT1_WAIT, 		DCC_DECODER_STATE_BIT1_0, 		100 },
			{ DCC_DECODER_STATE_BIT1_0, 		DCC_DECODER_STATE_BIT2_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT2_WAIT, 		DCC_DECODER_STATE_BIT2_0, 		100 },
			{ DCC_DECODER_STATE_BIT2_0, 		DCC_DECODER_STATE_BIT3_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT3_WAIT, 		DCC_DECODER_STATE_BIT3_0, 		100 },
			{ DCC_DECODER_STATE_BIT3_0, 		DCC_DECODER_STATE_BIT4_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT4_WAIT, 		DCC_DECODER_STATE_BIT4_0, 		100 },
			{ DCC_DECODER_STATE_BIT4_0, 		DCC_DECODER_STATE_BIT5_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT5_WAIT, 		DCC_DECODER_STATE_BIT5_0, 		100 },
			{ DCC_DECODER_STATE_BIT5_0, 		DCC_DECODER_STATE_BIT6_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT6_WAIT, 		DCC_DECODER_STATE_BIT6_0, 		100 },
			{ DCC_DECODER_STATE_BIT6_0, 		DCC_DECODER_STATE_BIT7_WAIT,		100 },
			{ DCC_DECODER_STATE_BIT7_WAIT, 		DCC_DECODER_STATE_BIT7_0, 		100 },
			{ DCC_DECODER_STATE_BIT7_0, 		DCC_DECODER_STATE_START_WAIT,		100 },
			{ DCC_DECODER_STATE_START_WAIT, 	DCC_DECODER_STATE_PREAMBLE_WAIT,	100, { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, 6, false },
			{ DCC_DECODER_STATE_PREAMBLE_WAIT,	DCC_DECODER_STATE_PREAMBLE_WAIT,	100, { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, 6, false },
			{ DCC_DECODER_STATE_PREAMBLE_WAIT,	DCC_DECODER_STATE_PREAMBLE_WAIT,	100 },
			{ DCC_DECODER_STATE_PREAMBLE_WAIT,	DCC_DECODER_STATE_PREAMBLE_WAIT,	100 },
			{ DCC_DECODER_STATE_PREAMBLE_WAIT,	DCC_DECODER_STATE_PREAMBLE_WAIT,	100 },
			{ DCC_DECODER_STATE_PREAMBLE_WAIT,	DCC_DECODER_STATE_PREAMBLE_WAIT,	100 },
			{ DCC_DECODER_STATE_PREAMBLE_WAIT,	DCC_DECODER_STATE_PREAMBLE_WAIT,	100 },
			{ DCC_DECODER_STATE_PREAMBLE_WAIT,	DCC_DECODER_STATE_PREAMBLE_WAIT,	100 },
			{ DCC_DECODER_STATE_PREAMBLE_WAIT,	DCC_DECODER_STATE_PREAMBLE_WAIT,	100 },
			{ DCC_DECODER_STATE_PREAMBLE_WAIT,	DCC_DECODER_STATE_PREAMBLE_WAIT,	100 },
			{ DCC_DECODER_STATE_PREAMBLE_WAIT,	DCC_DECODER_STATE_PREAMBLE_WAIT,	100 },
			{ DCC_DECODER_STATE_PREAMBLE_WAIT,	DCC_DECODER_STATE_PREAMBLE_WAIT,	100 },
			{ DCC_DECODER_STATE_PREAMBLE_WAIT,	DCC_DECODER_STATE_PREAMBLE_WAIT,	100 },
			{ DCC_DECODER_STATE_PREAMBLE_WAIT,	DCC_DECODER_STATE_PREAMBLE_WAIT,	100 },
			{ DCC_DECODER_STATE_PREAMBLE_WAIT,	DCC_DECODER_STATE_PREAMBLE_WAIT,	100 },
			{ DCC_DECODER_STATE_PREAMBLE_WAIT,	DCC_DECODER_STATE_PREAMBLE_WAIT,	100 },
			{ DCC_DECODER_STATE_PREAMBLE_WAIT,	DCC_DECODER_STATE_PREAMBLE_WAIT,	100 },
			{ DCC_DECODER_STATE_PREAMBLE_WAIT,	DCC_DECODER_STATE_PREAMBLE_WAIT,	100 },
			{ DCC_DECODER_STATE_PREAMBLE_WAIT, 	DCC_DECODER_STATE_PREAMBLE_0H,		58,  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, 6, false, false },
			{ DCC_DECODER_STATE_PREAMBLE_0H,	DCC_DECODER_STATE_PREAMBLE_1,		58,  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, 6, false, false },
			{ DCC_DECODER_STATE_PREAMBLE_1,		DCC_DECODER_STATE_PREAMBLE_1H, 		58,  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, 6, false, false },
			{ DCC_DECODER_STATE_PREAMBLE_1H,	DCC_DECODER_STATE_PREAMBLE_2, 		58,  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, 6, false, false },
			{ DCC_DECODER_STATE_PREAMBLE_2,		DCC_DECODER_STATE_PREAMBLE_2H, 		58,  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, 6, false, false },
			{ DCC_DECODER_STATE_PREAMBLE_2H,	DCC_DECODER_STATE_PREAMBLE_3, 		58,  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, 6, false, false },
			{ DCC_DECODER_STATE_PREAMBLE_3,		DCC_DECODER_STATE_PREAMBLE_3H, 		58,  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, 6, false, false },
			{ DCC_DECODER_STATE_PREAMBLE_3H,	DCC_DECODER_STATE_PREAMBLE_4, 		58,  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, 6, false, false },
			{ DCC_DECODER_STATE_PREAMBLE_4,		DCC_DECODER_STATE_PREAMBLE_4H, 		58,  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, 6, false, false },
			{ DCC_DECODER_STATE_PREAMBLE_4H,	DCC_DECODER_STATE_PREAMBLE_5, 		58,  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, 6, false, false },
			{ DCC_DECODER_STATE_PREAMBLE_5,		DCC_DECODER_STATE_PREAMBLE_5H, 		58,  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, 6, false, false },
			{ DCC_DECODER_STATE_PREAMBLE_5H,	DCC_DECODER_STATE_PREAMBLE_6, 		58,  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, 6, false, false },
			{ DCC_DECODER_STATE_PREAMBLE_6,		DCC_DECODER_STATE_PREAMBLE_6H, 		58,  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, 6, false, false },
			{ DCC_DECODER_STATE_PREAMBLE_6H,	DCC_DECODER_STATE_PREAMBLE_7, 		58,  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, 6, false, false },
			{ DCC_DECODER_STATE_PREAMBLE_7,		DCC_DECODER_STATE_PREAMBLE_7H, 		58,  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, 6, false, false },
			{ DCC_DECODER_STATE_PREAMBLE_7H,	DCC_DECODER_STATE_PREAMBLE_8, 		58,  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, 6, false, false },
			{ DCC_DECODER_STATE_PREAMBLE_8,		DCC_DECODER_STATE_PREAMBLE_8H, 		58,  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, 6, false, false },
			{ DCC_DECODER_STATE_PREAMBLE_8H,	DCC_DECODER_STATE_PREAMBLE_9, 		58,  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, 6, false, false },
			{ DCC_DECODER_STATE_PREAMBLE_9,		DCC_DECODER_STATE_PREAMBLE_9H, 		58,  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, 6, false, false },
			{ DCC_DECODER_STATE_PREAMBLE_9H,	DCC_DECODER_STATE_PREAMBLE_END,		58,  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, 6, false, false },
			{ DCC_DECODER_STATE_PREAMBLE_END, 	DCC_DECODER_STATE_START_H, 		100, {  }, 0, false, false },
			{ DCC_DECODER_STATE_START_H, 		DCC_DECODER_STATE_BIT0_WAIT,		100, {  }, 0, false, false },
		}
	
	},
};



struct test_handle {
	char *name;
	uint8_t packet[DCC_PACKET_MAX];
	int8_t len;
	bool received;

	uint8_t address_h;
	uint8_t address_l;

	bool reset_called;

	bool accessory_basic_called;
	uint16_t accessory_basic_add;
	uint8_t accessory_basic_pair;
	uint8_t accessory_basic_output;
	bool accessory_basic_value;
	
	bool accessory_extended_called;
	uint16_t accessory_extended_add;
	uint8_t accessory_extended_aspect;
	
	bool multifunction_speed_called;
	bool multifunction_speedstep_called;
	uint8_t speed;
	bool forward;

	bool multifunction_fg1_called;
	bool fl;
	bool f1;
	bool f2;
	bool f3;
	bool f4;
	
	bool multifunction_cv_write_called;
	bool multifunction_cv_writebit_called;
	uint16_t cv;
	uint8_t bit;
	uint8_t value;
};

struct test_handle test_handles[] = {
	{ "not", 	{ 0xff, 0x00, 0xff }, 3, false },
	{ "idle",	{ 0xff, 0x00, 0xff }, 3, true },
	{ "reset",	{ 0x00, 0x00, 0x00 }, 3, true, .reset_called = true },
	{ "basic acc min",  { 0x81, 0xf0, 0x71 }, 3, true,
		.accessory_basic_called = true,
		.accessory_basic_add = 1,
		.accessory_basic_pair = 0,
		.accessory_basic_output = 0,
		.accessory_basic_value = 0,
	},
	{ "basic acc bcast 0", { 0xbf, 0x88, 0x37 }, 3, true,
		.accessory_basic_called = true,
		.accessory_basic_add = 511,
		.accessory_basic_pair = 0,
		.accessory_basic_output = 0,
		.accessory_basic_value = 1,
	},
	{ "basic acc max (bcast 3)", { 0xbf, 0x87, 0x38 }, 3, true,
		.accessory_basic_called = true,
		.accessory_basic_add = 511,
		.accessory_basic_pair = 3,
		.accessory_basic_output = 1,
		.accessory_basic_value = 0,
	},
	{ "basic acc 1 pair 3 pin 1",  { 0x81, 0xff, 0x7e }, 3, true,
		.accessory_basic_called = true,
		.accessory_basic_add = 1,
		.accessory_basic_pair = 3,
		.accessory_basic_output = 1,
		.accessory_basic_value = 1,
	},
	{ "basic acc 2 pair 1 pin 0",  { 0x82, 0xfa, 0x78 }, 3, true,
		.accessory_basic_called = true,
		.accessory_basic_add = 2,
		.accessory_basic_pair = 1,
		.accessory_basic_output = 0,
		.accessory_basic_value = 1,
	},
	{ "basic acc cv",  { 0x81, 0xf0, 0xec, 0x00, 0x00, 0x9d }, 6, true,
		.accessory_basic_called = false,
	},
	{ "extended acc 1 aspect 0",  { 0x81, 0x71, 0x00, 0xf0 }, 4, true,
		.accessory_extended_called = true,
		.accessory_extended_add = 1,
		.accessory_extended_aspect = 0,
	},
	{ "extended acc 11 aspect 1",  { 0x83, 0x75, 0x01, 0xf7 }, 4, true,
		.accessory_extended_called = true,
		.accessory_extended_add = 11,
		.accessory_extended_aspect = 1,
	},
	{ "extended acc 15 aspect 16",  { 0x84, 0x75, 0x10, 0xe1 }, 4, true,
		.accessory_extended_called = true,
		.accessory_extended_add = 15,
		.accessory_extended_aspect = 16,
	},
 	{ "extended acc 2044 aspect 255",  { 0xbf, 0x07, 0xff, 0x47 }, 4, true,
		.accessory_extended_called = true,
		.accessory_extended_add = 2044,
		.accessory_extended_aspect = 255,
	},
	
	{ "multifunction address 3 speed 28 forward", { 0x03, 0x7f, 0x7c }, 3, true,
		.multifunction_speed_called = true,
		.speed = 0x1f,
		.forward = true,
		.address_h = 0,
		.address_l = 3,
	},
	{ "multifunction address 3 speed 28 reverse", { 0x03, 0x5f, 0x5c }, 3, true,
		.multifunction_speed_called = true,
		.speed = 0x1f,
		.forward = false,
		.address_h = 0,
		.address_l = 3,
	},
	{ "multifunction address 3 speed 1 forward", { 0x03, 0x62, 0x61 }, 3, true,
		.multifunction_speed_called = true,
		.speed = 2,
		.forward = true,
		.address_h = 0,
		.address_l = 3,
	},
	{ "multifunction address 3 speed stop reverse", { 0x03, 0x40, 0x43 }, 3, true,
		.multifunction_speed_called = true,
		.speed = 0,
		.forward = false,
		.address_h = 0,
		.address_l = 3,
	},
	{ "multifunction address 1234 speed 28 forward", { 0xc4, 0xd2, 0x7f, 0x69 }, 4, true,
		.multifunction_speed_called = true,
		.speed = 0x1f,
		.forward = true,
		.address_h = 196,
		.address_l = 210,
	},
	{ "multifunction address 1234 speed 28 reverse", { 0xc4, 0xd2, 0x5f, 0x49 }, 4, true,
		.multifunction_speed_called = true,
		.speed = 0x1f,
		.forward = false,
		.address_h = 196,
		.address_l = 210,
	},
	{ "multifunction address 1234 speedstep 0 forward", { 0xc4, 0xd2, 0x3f, 0x80, 0xa9 }, 5, true,
		.multifunction_speedstep_called = true,
		.speed = 0,
		.forward = true,
		.address_h = 196,
		.address_l = 210,
	},
	{ "multifunction address 1234 speedstep 126 reverse", { 0xc4, 0xd2, 0x3f, 0x00, 0x29 }, 5, true,
		.multifunction_speedstep_called = true,
		.speed = 127,
		.forward = false,
		.address_h = 196,
		.address_l = 210,
	},


	{ "multifunction address 3 fg1 all off", { 0x03, 0x80, 0x83 }, 3, true,
		.multifunction_fg1_called = true,
		.address_h = 0,
		.address_l = 3,
		.fl = 0,
		.f1 = 0,
		.f2 = 0,
		.f3 = 0,
		.f4 = 0,
	},
	{ "multifunction address 3 fg1 FL", { 0x03, 0x90, 0x93 }, 3, true,
		.multifunction_fg1_called = true,
		.address_h = 0,
		.address_l = 3,
		.fl = 1,
		.f1 = 0,
		.f2 = 0,
		.f3 = 0,
		.f4 = 0,
	},
	{ "multifunction address 3 fg1 F1", { 0x03, 0x81, 0x82 }, 3, true,
		.multifunction_fg1_called = true,
		.address_h = 0,
		.address_l = 3,
		.fl = 0,
		.f1 = 1,
		.f2 = 0,
		.f3 = 0,
		.f4 = 0,
	},
	{ "multifunction address 3 fg1 F2", { 0x03, 0x82, 0x81 }, 3, true,
		.multifunction_fg1_called = true,
		.address_h = 0,
		.address_l = 3,
		.fl = 0,
		.f1 = 0,
		.f2 = 1,
		.f3 = 0,
		.f4 = 0,
	},
	{ "multifunction address 3 fg1 F3", { 0x03, 0x84, 0x87 }, 3, true,
		.multifunction_fg1_called = true,
		.address_h = 0,
		.address_l = 3,
		.fl = 0,
		.f1 = 0,
		.f2 = 0,
		.f3 = 1,
		.f4 = 0,
	},
	{ "multifunction address 3 fg1 F4", { 0x03, 0x88, 0x8b }, 3, true,
		.multifunction_fg1_called = true,
		.address_h = 0,
		.address_l = 3,
		.fl = 0,
		.f1 = 0,
		.f2 = 0,
		.f3 = 0,
		.f4 = 1,
	},
	
	{ "cv write cv1 bit 0 1 @ 51", { 0x33, 0xe8, 0x00, 0xf8, 0x23 }, 5, true,
		.multifunction_cv_writebit_called = true,
		.address_h = 0,
		.address_l = 51,
		.cv = 1,
		.bit = 0,
		.value = 1,
	},
	{ "cv write cv1 bit 1 0 @ 51", { 0x33, 0xe8, 0x00, 0xf1, 0x2a }, 5, true,
		.multifunction_cv_writebit_called = true,
		.address_h = 0,
		.address_l = 51,
		.cv = 1,
		.bit = 1,
		.value = 0
	},
	{ "cv write cv1 bit 7 1 @ 51", { 0x33, 0xe8, 0x00, 0xff, 0x24 }, 5, true,
		.multifunction_cv_writebit_called = true,
		.address_h = 0,
		.address_l = 51,
		.cv = 1,
		.bit = 7,
		.value = 1,
	},

	{ "cv write cv1 0x5a @ 51", { 0x33, 0xec, 0x00, 0x5a, 0x85 }, 5, true,
		.multifunction_cv_write_called = true,
		.address_h = 0,
		.address_l = 51,
		.cv = 1,
		.value = 0x5a,
	},
	{ "cv write cv769 0x5a @ 1", { 0x33, 0xef, 0x00, 0x5a, 0x86 }, 5, true,
		.multifunction_cv_write_called = true,
		.address_h = 0,
		.address_l = 51,
		.cv = 769,
		.value = 0x5a,
	},
	{ "cv write cv1024 0xa5 @ 1", { 0x33, 0xef, 0xff, 0xa5, 0x86 }, 5, true,
		.multifunction_cv_write_called = true,
		.address_h = 0,
		.address_l = 51,
		.cv = 1024,
		.value = 0xa5,
	},
	{ "cv write cv1024 0xa5 @ 1234", { 0xc4, 0xd2, 0xef, 0xff, 0xa5, 0xa3 }, 6, true,
		.multifunction_cv_write_called = true,
		.address_h = 196,
		.address_l = 210,
		.cv = 1024,
		.value = 0xa5,
	},
};

bool dcc_handle_reset_called;
uint8_t dcc_handle_address_h = -1;
uint8_t dcc_handle_address_l = -1;
void dcc_handle_reset(uint8_t address_h, uint8_t address_l)
{
	dcc_handle_address_h = address_h;
	dcc_handle_address_l = address_l;
	dcc_handle_reset_called = true;
}

bool dcc_handle_accessory_basic_called;
uint16_t dcc_handle_accessory_basic_add;
uint8_t dcc_handle_accessory_basic_pair;
uint8_t dcc_handle_accessory_basic_output;
bool dcc_handle_accessory_basic_value;
void dcc_handle_accessory_basic(uint16_t add, uint8_t pair, uint8_t output, bool value)
{
	dcc_handle_accessory_basic_called = true;
	dcc_handle_accessory_basic_add = add;
	dcc_handle_accessory_basic_pair = pair;
	dcc_handle_accessory_basic_output = output;
	dcc_handle_accessory_basic_value = value;
}

bool dcc_handle_accessory_extended_called;
uint16_t dcc_handle_accessory_extended_output_address;
uint8_t dcc_handle_accessory_extended_aspect;
void dcc_handle_accessory_extended(uint16_t output_address, uint8_t aspect)
{
	dcc_handle_accessory_extended_called = true;
	dcc_handle_accessory_extended_output_address = output_address;
	dcc_handle_accessory_extended_aspect = aspect;
}

bool dcc_handle_multifunction_speed_called;
uint8_t dcc_handle_speed;
bool dcc_handle_forward;
void dcc_handle_multifunction_speed(uint8_t address_h, uint8_t address_l, uint8_t speed, bool forward)
{
	dcc_handle_multifunction_speed_called = true;
	dcc_handle_address_h = address_h;
	dcc_handle_address_l = address_l;
	dcc_handle_speed = speed;
	dcc_handle_forward = forward;
}
bool dcc_handle_multifunction_speedstep_called;
void dcc_handle_multifunction_speedstep(uint8_t address_h, uint8_t address_l, uint8_t speed, bool forward)
{
	dcc_handle_multifunction_speedstep_called = true;
	dcc_handle_address_h = address_h;
	dcc_handle_address_l = address_l;
	dcc_handle_speed = speed;
	dcc_handle_forward = forward;
}

bool dcc_handle_multifunction_fg1_called;
bool dcc_handle_fl;
bool dcc_handle_f1;
bool dcc_handle_f2;
bool dcc_handle_f3;
bool dcc_handle_f4;
void dcc_handle_multifunction_fg1(uint8_t address_h, uint8_t address_l, bool fl, bool f1, bool f2, bool f3, bool f4)
{
	dcc_handle_multifunction_fg1_called = true;
	dcc_handle_address_h = address_h;
	dcc_handle_address_l = address_l;
	dcc_handle_fl = fl;
	dcc_handle_f1 = f1;
	dcc_handle_f2 = f2;
	dcc_handle_f3 = f3;
	dcc_handle_f4 = f4;
}


bool dcc_handle_multifunction_cv_write_called;
uint16_t dcc_handle_cv;
uint8_t dcc_handle_value;
void dcc_handle_multifunction_cv_write(uint8_t address_h, uint8_t address_l, uint16_t cv, uint8_t value)
{
	dcc_handle_multifunction_cv_write_called = true;
	dcc_handle_address_h = address_h;
	dcc_handle_address_l = address_l;
	dcc_handle_cv = cv;
	dcc_handle_value = value;
}
bool dcc_handle_multifunction_cv_writebit_called;
uint8_t dcc_handle_bit;
void dcc_handle_multifunction_cv_writebit(uint8_t address_h, uint8_t address_l, uint16_t cv, uint8_t bit, bool value)
{
	dcc_handle_multifunction_cv_writebit_called = true;
	dcc_handle_address_h = address_h;
	dcc_handle_address_l = address_l;
	dcc_handle_bit = bit;
	dcc_handle_cv = cv;
	dcc_handle_value = value;
}



int main(int argc, char **argv)
{
	int i;
	int r = 0;
	uint16_t ticks = 0;
	
	printf("ut_dcc_decoder:\n");
	
	for (i = 0; i < sizeof(tests)/sizeof(tests[0]); i ++) {
		int r_test = 0;
		TICK_US = tests[i].tick_us;
		printf("Test: %s: (TICK_US=%d) ", tests[i].name, TICK_US);
		
		dcc_packet_len = 0;
		dcc_packet_received = 0;
		
		int step;
		for (step = 0; step < tests[i].nr; step++) {
			dcc_decoder_state = tests[i].steps[step].state_in;
			dcc_packet_received = tests[i].steps[step].received_in;
			
			ticks += tests[i].steps[step].tick;

			/******************
			    Perform test
			 *****************/
		
			dcc_toggle(ticks);

			/******************
			    Check
			 *****************/
			
			if (dcc_decoder_state != tests[i].steps[step].state_out) {
				r_test++;
				printf("Step %d: expected %d -> %d, got %d\n", step, tests[i].steps[step].state_in, tests[i].steps[step].state_out, dcc_decoder_state);
			}
			
			if (tests[i].steps[step].len) {
				if (tests[i].steps[step].len != dcc_packet_len) {
					r_test++;
					printf("Step %d: len expected %d, got %d\n", step, tests[i].steps[step].len, dcc_packet_len);
				}
				if (tests[i].steps[step].received_out != dcc_packet_received) {
					r_test++;
					printf("Step %d: received expected %d, got %d\n", step, tests[i].steps[step].received_out, dcc_packet_received);
				}
				int j;
				for (j = 0; j < tests[i].steps[step].len; j++) {
					if (tests[i].steps[step].packet[j] != dcc_packet[j]) {
						r_test++;
						printf("Step %d: pos %d expected 0x%02x, got 0x%02x\n", step, j, tests[i].steps[step].packet[j], dcc_packet[j]);
					}
				}
			}
		}
		
		if (r_test == 0) {
			printf("PASS\n");
		} else {
			printf("FAIL\n");
		}
		r += r_test;
	}

	for (i = 0; i < sizeof(test_handles)/sizeof(test_handles[0]); i++) {
		int r_test = 0;
		printf("Test: %s: ", test_handles[i].name);

		memcpy((void*)dcc_packet, test_handles[i].packet, DCC_PACKET_MAX);
		dcc_packet_len = test_handles[i].len;
		dcc_packet_received = test_handles[i].received;
		
		dcc_handle_reset_called = false;
		dcc_handle_accessory_basic_called = false;
		dcc_handle_accessory_extended_called = false;
		dcc_handle_multifunction_speed_called = false;
		dcc_handle_multifunction_speedstep_called = false;
		dcc_handle_multifunction_fg1_called = false;
		dcc_handle_multifunction_cv_writebit_called = false;
		dcc_handle_multifunction_cv_write_called = false;
		
		/******************
		    Perform test
		 *****************/
		
		dcc_decoder_handle();
		
		/******************
		    Check
		 *****************/
		
		if (dcc_packet_received) {
			r_test++;
			printf("received state not reset as expected\n");
		}

		if (test_handles[i].reset_called != dcc_handle_reset_called) {
			r_test++;
			printf("reset handler not/unexpected called\n");
		}
		if (test_handles[i].reset_called && (dcc_handle_address_l != 0 || dcc_handle_address_h != 0)) {
			r_test++;
			printf("reset handler called with bad address 0x%02x 0x%02x\n", dcc_handle_address_h, dcc_handle_address_l);
		}

		if (test_handles[i].accessory_basic_called != dcc_handle_accessory_basic_called) {
			r_test++;
			printf("basic accessory handler not/unexpected called\n");
		}
		if (test_handles[i].accessory_basic_called) {
			if (dcc_handle_accessory_basic_add != test_handles[i].accessory_basic_add)
				r_test++;
			if (dcc_handle_accessory_basic_pair != test_handles[i].accessory_basic_pair)
				r_test++;
			if (dcc_handle_accessory_basic_output != test_handles[i].accessory_basic_output)
				r_test++;
			if (dcc_handle_accessory_basic_value != test_handles[i].accessory_basic_value)
				r_test++;
			
			if (r_test) {
				printf("basic accessory handler not correctly called: (%d, %d, %d, %d)\n",
				    dcc_handle_accessory_basic_add,
				    dcc_handle_accessory_basic_pair,
				    dcc_handle_accessory_basic_output,
				    dcc_handle_accessory_basic_value);
			}
		}

		if (test_handles[i].accessory_extended_called != dcc_handle_accessory_extended_called) {
			r_test++;
			printf("extended accessory handler not/unexpected called\n");
		}
		if (test_handles[i].accessory_extended_called) {
			if (dcc_handle_accessory_extended_output_address != test_handles[i].accessory_extended_add)
				r_test++;
			if (dcc_handle_accessory_extended_aspect != test_handles[i].accessory_extended_aspect)
				r_test++;
			if (r_test) {
				printf("extended accessory handler not correctly called: (%d, %d)\n",
				    dcc_handle_accessory_extended_output_address,
				    dcc_handle_accessory_extended_aspect);
			}
		}
		
		if (test_handles[i].multifunction_speed_called != dcc_handle_multifunction_speed_called) {
			r_test++;
			printf("multifunction speed handler not/unexpected called: %d\n", dcc_handle_multifunction_speed_called);
		}
		if (test_handles[i].multifunction_speed_called) {
			if (test_handles[i].speed != dcc_handle_speed) {
				r_test++;
			}
			if (test_handles[i].forward != dcc_handle_forward) {
				r_test++;
			}
			if (test_handles[i].address_l != dcc_handle_address_l) {
				r_test++;
			}
			if (test_handles[i].address_h != dcc_handle_address_h) {
				r_test++;
			}
			if (r_test) {
				printf("speed not properly set: (%d, %d) @ 0x%02x 0x%02x\n", 
				    dcc_handle_speed, dcc_handle_forward, dcc_handle_address_h, dcc_handle_address_l);
			}
		}

		
		if (test_handles[i].multifunction_fg1_called != dcc_handle_multifunction_fg1_called) {
			r_test++;
			printf("multifunction fg1 handler not/unexpected called: %d\n", dcc_handle_multifunction_fg1_called);
		}
		if (test_handles[i].multifunction_fg1_called) {
			if (test_handles[i].fl != dcc_handle_fl) {
				r_test++;
			}
			if (test_handles[i].f1 != dcc_handle_f1) {
				r_test++;
			}
			if (test_handles[i].f2 != dcc_handle_f2) {
				r_test++;
			}
			if (test_handles[i].f3 != dcc_handle_f3) {
				r_test++;
			}
			if (test_handles[i].f4 != dcc_handle_f4) {
				r_test++;
			}
			if (test_handles[i].address_l != dcc_handle_address_l) {
				r_test++;
			}
			if (test_handles[i].address_h != dcc_handle_address_h) {
				r_test++;
			}
			if (r_test) {
				printf("fg1 not properly set: (%d, %d, %d, %d, %d) @ 0x%02x 0x%02x\n", 
				    dcc_handle_fl, dcc_handle_f1, dcc_handle_f2, dcc_handle_f3, dcc_handle_f4, dcc_handle_address_h, dcc_handle_address_l);
			}
		}


		if (test_handles[i].multifunction_cv_writebit_called != dcc_handle_multifunction_cv_writebit_called) {
			r_test++;
			printf("multifunction cv writebit handler not/unexpected called: %d\n", dcc_handle_multifunction_cv_writebit_called);
		}
		if (test_handles[i].multifunction_cv_writebit_called) {
			if (test_handles[i].address_l != dcc_handle_address_l) {
				r_test++;
			}
			if (test_handles[i].address_h != dcc_handle_address_h) {
				r_test++;
			}
			if (test_handles[i].cv != dcc_handle_cv) {
				r_test++;
			}
			if (test_handles[i].bit != dcc_handle_bit) {
				r_test++;
			}
			if (test_handles[i].value != dcc_handle_value) {
				r_test++;
			}
			if (r_test) {
				printf("cvbit not properly written: (%d, %d, %d) @ 0x%02x 0x%02x\n",
				    dcc_handle_cv, dcc_handle_bit, dcc_handle_value, dcc_handle_address_h, dcc_handle_address_l);
			}
		}
		
		if (test_handles[i].multifunction_cv_write_called != dcc_handle_multifunction_cv_write_called) {
			r_test++;
			printf("multifunction cv write handler not/unexpected called: %d\n", dcc_handle_multifunction_cv_write_called);
		}
		if (test_handles[i].multifunction_cv_write_called) {
			if (test_handles[i].address_l != dcc_handle_address_l) {
				r_test++;
			}
			if (test_handles[i].address_h != dcc_handle_address_h) {
				r_test++;
			}
			if (test_handles[i].cv != dcc_handle_cv) {
				r_test++;
			}
			if (test_handles[i].value != dcc_handle_value) {
				r_test++;
			}
			if (r_test) {
				printf("cv not properly written: (%d, 0x%02x) @ 0x%02x 0x%02x\n",
				    dcc_handle_cv, dcc_handle_value, dcc_handle_address_h, dcc_handle_address_l);
			}
		}
		
		if (r_test == 0) {
			printf("PASS\n");
		} else {
			printf("FAIL\n");
		}
		r += r_test;
	}

	if (r) {
		printf("Tests failed: %d\n", r);
	} else {
		printf("All tests pass\n");
	}

	return r;
}
